### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by chde222** [alienzhou/server_push_demo#1]
在运行代码时，发现index界面没有博主展示的那个input输入框。根本无从下手对比那几个技术，请问下博主可以重新发一个吗

**Comment by alienzhou** [comment]
不好意思这两天有点忙，才回复。

demo其实包含两个页面：
- 一个是 http://localhost:8080/ ，用于接受与展示提交的信息（图里左边部分）；
- 另一个是 http://localhost:8080/post ，用于提交信息（右边部分，也就是那个input框）

示例图是分屏录的，所以其实是两个tab页面。

这个在readme里没写清楚，我补充一下，感谢反馈😊

**Comment by chde222** [comment]
嗯嗯，看了代码最后找到post页面了。可是确定后运行就报错。点击submit就报错
![image](https://user-images.githubusercontent.com/45227620/56783528-c2526c80-681e-11e9-92b8-514f8ed33e1b.png)
调了好长时间也没有调通  哭！！

**Comment by alienzhou** [comment]
看报错像是 websocket 这个库里报出来的问题。建议试试升级node或者重新安装依赖。

https://github.com/theturtle32/WebSocket-Node/issues/335#issue-379511907

**Comment by chde222** [comment]
问题解决了，谢谢您的代码和您的耐心解答

**Comment by alienzhou** [comment]
不客气😁
